# @package _global_

defaults:
  - override /dataset: co3d_hydrant

dataset:
  view_sampler:
    index_path: assets/evaluation_index/co3d_hydrant_extra.json

evaluation:
  methods:
    - name: Ours
      key: ours
      path: outputs/test/co3d_hydrant_extra
    - name: Deterministic
      key: det
      path: outputs/ablation/co3d_hydrant_det
    - name: No Skip
      key: no_skip
      path: outputs/ablation/co3d_hydrant_no_skip
    - name: No RGB Skip
      key: no_extra
      path: outputs/ablation/co3d_hydrant_no_extra

  side_by_side_path: null
  animate_side_by_side: false
  highlighted:
    - scene: '185_19990_38942'
      context_index: [17, 37]
      target_index: 84
    - scene: '235_24641_51707'
      context_index: [57, 73]
      target_index: 86

output_metrics_path: ablations/co3d_hydrant_extra/evaluation_metrics.json
per_scene_metrics_path: ablations/co3d_hydrant_extra/per_scene_metrics.json