name: kl
model: kl_f32

down_block_types:
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - AttnDownEncoderBlock2D
  - AttnDownEncoderBlock2D
up_block_types:
  - AttnUpDecoderBlock2D
  - AttnUpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
block_out_channels: [128, 128, 256, 256, 512, 512]
layers_per_block: 2
latent_channels: 64
