name: kl
model: kl_f8

down_block_types: 
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - DownEncoderBlock2D
  - DownEncoderBlock2D
up_block_types:
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
  - UpDecoderBlock2D
block_out_channels: [128, 256, 512, 512]
layers_per_block: 2
latent_channels: 4
skip_connections: true
skip_extra: true
skip_zero: true